### ISSUE TITLE
Sequential campaign_id may lead to collision

### ISSUE THREAD

**Issue by frol** [agileurbanite/contracts.near-linkdrop#17]
If one creates two campaigns in the same transaction, we will arrive with two cross-contract calls of creating two campaigns with the same `campaign_id` (the counter will be incremented correctly, but we will have `future_campaight_id = 3` while two campaigns will have `campaign_id = 1`).

https://github.com/NEAR-labs/contracts.near-linkdrop/blob/6f7fa859ac1313838797745bc6cd7e59847fc455/contracts/user/src/create_near_campaign.rs#L27

**Comment by eclipseeer** [comment]
As I understand there is no way to get this problem only if the campaign owner will try to hack his own campaign - he will manually create a transaction with 2 'create_near_campaign' actions. Do I understand correctly that 2 transactions signed by 1 key and called in parallel won't be a cause of this problem? Even though this corruption won't be critical, of course, it is better to avoid it. Do you have an idea how to fix it?

**Comment by frol** [comment]
Yeah, well I feel some software / network glitch will have a higher chance than people hacking their own campaigns. I think we can live with the current state of things

**Comment by eclipseeer** [comment]
Yeah, anyway I think we can remove this field in the v2 - we use it only as an id for key generation on the frontend. As we are using the same seed phrase for multiply campaigns, we need some unique id to make keys (links with drop) not be the same for the different campaigns.

But I think we can use campaign account id for this purpose as well
